import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Check, CheckCircle, CreditCard, Wallet, Building, ArrowLeft, Lock, Truck, Shield, Banknote } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { Textarea } from '@/components/ui/textarea';
import { useCart } from '@/hooks/useCart';
import { useAuth } from '@/hooks/useAuth';
import { supabase } from '@/integrations/supabase/client';
import { cn } from '@/lib/utils';
import { toast } from 'sonner';
import { z } from 'zod';

const steps = ['Information', 'Shipping', 'Payment'];

const informationSchema = z.object({
  firstName: z.string().min(2, 'First name is required').max(50),
  lastName: z.string().min(2, 'Last name is required').max(50),
  email: z.string().email('Valid email is required'),
  phone: z.string().min(10, 'Valid phone number is required').max(15),
});

const shippingSchema = z.object({
  address: z.string().min(5, 'Address is required').max(200),
  city: z.string().min(2, 'City is required').max(50),
  state: z.string().min(2, 'State is required').max(50),
  pincode: z.string().min(6, 'Valid PIN code is required').max(6),
});

export default function Checkout() {
  const { items, totalPrice, clearCart } = useCart();
  const { user } = useAuth();
  const navigate = useNavigate();
  
  const [currentStep, setCurrentStep] = useState(0);
  const [paymentMethod, setPaymentMethod] = useState('card');
  const [isProcessing, setIsProcessing] = useState(false);
  const [errors, setErrors] = useState<Record<string, string>>({});
  
  // Form data
  const [formData, setFormData] = useState({
    firstName: '',
    lastName: '',
    email: user?.email || '',
    phone: '',
    address: '',
    city: '',
    state: '',
    pincode: '',
    notes: '',
  });

  const formatPrice = (price: number) => {
    return new Intl.NumberFormat('en-IN', {
      style: 'currency',
      currency: 'INR',
      maximumFractionDigits: 0,
    }).format(price);
  };

  const shipping = totalPrice > 2000 ? 0 : 199;
  const tax = Math.round(totalPrice * 0.18); // 18% GST
  const finalTotal = totalPrice + shipping + tax;

  const updateFormData = (field: string, value: string) => {
    setFormData(prev => ({ ...prev, [field]: value }));
    if (errors[field]) {
      setErrors(prev => ({ ...prev, [field]: '' }));
    }
  };

  const validateStep = (step: number): boolean => {
    try {
      if (step === 0) {
        informationSchema.parse({
          firstName: formData.firstName,
          lastName: formData.lastName,
          email: formData.email,
          phone: formData.phone,
        });
      } else if (step === 1) {
        shippingSchema.parse({
          address: formData.address,
          city: formData.city,
          state: formData.state,
          pincode: formData.pincode,
        });
      }
      setErrors({});
      return true;
    } catch (error) {
      if (error instanceof z.ZodError) {
        const newErrors: Record<string, string> = {};
        error.errors.forEach(err => {
          if (err.path[0]) {
            newErrors[err.path[0] as string] = err.message;
          }
        });
        setErrors(newErrors);
      }
      return false;
    }
  };

  const handleNextStep = () => {
    if (validateStep(currentStep) && currentStep < steps.length - 1) {
      setCurrentStep(currentStep + 1);
    }
  };

  const handlePrevStep = () => {
    if (currentStep > 0) {
      setCurrentStep(currentStep - 1);
    }
  };

  const handlePlaceOrder = async () => {
    if (!user) {
      toast.error('Please sign in to place an order');
      navigate('/auth');
      return;
    }

    setIsProcessing(true);

    try {
      // Create order - order_number is auto-generated by database trigger
      const { data: orderData, error: orderError } = await supabase
        .from('orders')
        .insert({
          user_id: user.id,
          order_number: `CRK-${Date.now()}`, // Temporary - will be overwritten by trigger
          subtotal: totalPrice,
          tax: tax,
          shipping: shipping,
          total: finalTotal,
          shipping_name: `${formData.firstName} ${formData.lastName}`,
          shipping_email: formData.email,
          shipping_phone: formData.phone,
          shipping_address: formData.address,
          shipping_city: formData.city,
          shipping_state: formData.state,
          shipping_postal_code: formData.pincode,
          payment_method: paymentMethod,
          notes: formData.notes,
          status: 'pending',
        })
        .select()
        .single();

      if (orderError) throw orderError;

      // Create order items
      const orderItems = items.map(item => ({
        order_id: orderData.id,
        product_id: item.product.id,
        product_name: item.product.name,
        product_image: item.product.image,
        quantity: item.quantity,
        price: item.product.price,
      }));

      const { error: itemsError } = await supabase
        .from('order_items')
        .insert(orderItems);

      if (itemsError) throw itemsError;

      // Clear cart and navigate to success page
      clearCart();
      navigate('/order-success', { 
        state: { 
          orderData: {
            orderId: orderData.id,
            orderNumber: orderData.order_number,
            total: finalTotal,
          }
        }
      });
      
    } catch (error) {
      console.error('Error placing order:', error);
      toast.error('Failed to place order. Please try again.');
    } finally {
      setIsProcessing(false);
    }
  };

  if (items.length === 0) {
    return (
      <main className="min-h-screen py-16">
        <div className="container mx-auto px-4 text-center">
          <h1 className="font-display text-4xl mb-4">No Items to Checkout</h1>
          <Button asChild>
            <Link to="/products">Browse Products</Link>
          </Button>
        </div>
      </main>
    );
  }

  return (
    <main className="min-h-screen py-8">
      <div className="container mx-auto px-4">
        {/* Header */}
        <div className="flex items-center gap-4 mb-8">
          <Button variant="ghost" size="icon" asChild>
            <Link to="/cart">
              <ArrowLeft className="h-5 w-5" />
            </Link>
          </Button>
          <h1 className="font-display text-3xl md:text-4xl">CHECKOUT</h1>
        </div>

        {/* Guest Checkout Notice */}
        {!user && (
          <div className="mb-8 p-4 bg-primary/10 rounded-xl flex items-center justify-between">
            <p className="text-sm">
              <strong>Save your order history!</strong> Sign in to track your orders and save your wishlist.
            </p>
            <Button size="sm" asChild>
              <Link to="/auth">Sign In</Link>
            </Button>
          </div>
        )}

        {/* Progress Steps */}
        <div className="flex items-center justify-center gap-4 mb-12">
          {steps.map((step, index) => (
            <div key={step} className="flex items-center">
              <div
                className={cn(
                  'w-8 h-8 rounded-full flex items-center justify-center font-semibold text-sm transition-colors',
                  index <= currentStep
                    ? 'bg-primary text-primary-foreground'
                    : 'bg-muted text-muted-foreground'
                )}
              >
                {index < currentStep ? <Check className="h-4 w-4" /> : index + 1}
              </div>
              <span
                className={cn(
                  'ml-2 text-sm hidden sm:block',
                  index <= currentStep ? 'text-foreground' : 'text-muted-foreground'
                )}
              >
                {step}
              </span>
              {index < steps.length - 1 && (
                <div
                  className={cn(
                    'w-12 md:w-24 h-0.5 mx-4',
                    index < currentStep ? 'bg-primary' : 'bg-muted'
                  )}
                />
              )}
            </div>
          ))}
        </div>

        <div className="grid lg:grid-cols-3 gap-8">
          {/* Form */}
          <div className="lg:col-span-2">
            <motion.div
              key={currentStep}
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              className="bg-card rounded-2xl border border-border p-6 md:p-8"
            >
              {/* Step 1: Information */}
              {currentStep === 0 && (
                <div className="space-y-6">
                  <h2 className="font-display text-xl mb-6">CONTACT INFORMATION</h2>
                  
                  <div className="grid md:grid-cols-2 gap-4">
                    <div>
                      <Label htmlFor="firstName">First Name *</Label>
                      <Input 
                        id="firstName" 
                        placeholder="Virat" 
                        className="mt-1"
                        value={formData.firstName}
                        onChange={(e) => updateFormData('firstName', e.target.value)}
                      />
                      {errors.firstName && <p className="text-sm text-destructive mt-1">{errors.firstName}</p>}
                    </div>
                    <div>
                      <Label htmlFor="lastName">Last Name *</Label>
                      <Input 
                        id="lastName" 
                        placeholder="Kohli" 
                        className="mt-1"
                        value={formData.lastName}
                        onChange={(e) => updateFormData('lastName', e.target.value)}
                      />
                      {errors.lastName && <p className="text-sm text-destructive mt-1">{errors.lastName}</p>}
                    </div>
                  </div>

                  <div>
                    <Label htmlFor="email">Email *</Label>
                    <Input 
                      id="email" 
                      type="email" 
                      placeholder="virat@example.com" 
                      className="mt-1"
                      value={formData.email}
                      onChange={(e) => updateFormData('email', e.target.value)}
                    />
                    {errors.email && <p className="text-sm text-destructive mt-1">{errors.email}</p>}
                  </div>

                  <div>
                    <Label htmlFor="phone">Phone Number *</Label>
                    <Input 
                      id="phone" 
                      type="tel" 
                      placeholder="9876543210" 
                      className="mt-1"
                      value={formData.phone}
                      onChange={(e) => updateFormData('phone', e.target.value)}
                    />
                    {errors.phone && <p className="text-sm text-destructive mt-1">{errors.phone}</p>}
                  </div>

                  <Button className="w-full" onClick={handleNextStep}>
                    Continue to Shipping
                  </Button>
                </div>
              )}

              {/* Step 2: Shipping */}
              {currentStep === 1 && (
                <div className="space-y-6">
                  <h2 className="font-display text-xl mb-6">SHIPPING ADDRESS</h2>

                  <div>
                    <Label htmlFor="address">Street Address *</Label>
                    <Input 
                      id="address" 
                      placeholder="123 Cricket Lane, Apt 4B" 
                      className="mt-1"
                      value={formData.address}
                      onChange={(e) => updateFormData('address', e.target.value)}
                    />
                    {errors.address && <p className="text-sm text-destructive mt-1">{errors.address}</p>}
                  </div>

                  <div className="grid md:grid-cols-2 gap-4">
                    <div>
                      <Label htmlFor="city">City *</Label>
                      <Input 
                        id="city" 
                        placeholder="Mumbai" 
                        className="mt-1"
                        value={formData.city}
                        onChange={(e) => updateFormData('city', e.target.value)}
                      />
                      {errors.city && <p className="text-sm text-destructive mt-1">{errors.city}</p>}
                    </div>
                    <div>
                      <Label htmlFor="state">State *</Label>
                      <Input 
                        id="state" 
                        placeholder="Maharashtra" 
                        className="mt-1"
                        value={formData.state}
                        onChange={(e) => updateFormData('state', e.target.value)}
                      />
                      {errors.state && <p className="text-sm text-destructive mt-1">{errors.state}</p>}
                    </div>
                  </div>

                  <div className="grid md:grid-cols-2 gap-4">
                    <div>
                      <Label htmlFor="pincode">PIN Code *</Label>
                      <Input 
                        id="pincode" 
                        placeholder="400001" 
                        className="mt-1"
                        value={formData.pincode}
                        onChange={(e) => updateFormData('pincode', e.target.value)}
                      />
                      {errors.pincode && <p className="text-sm text-destructive mt-1">{errors.pincode}</p>}
                    </div>
                    <div>
                      <Label htmlFor="country">Country</Label>
                      <Input id="country" value="India" disabled className="mt-1" />
                    </div>
                  </div>

                  <div>
                    <Label htmlFor="notes">Order Notes (Optional)</Label>
                    <Textarea 
                      id="notes" 
                      placeholder="Any special instructions for delivery..."
                      className="mt-1"
                      value={formData.notes}
                      onChange={(e) => updateFormData('notes', e.target.value)}
                    />
                  </div>

                  <div className="flex gap-4">
                    <Button variant="outline" onClick={handlePrevStep} className="flex-1">
                      Back
                    </Button>
                    <Button onClick={handleNextStep} className="flex-1">
                      Continue to Payment
                    </Button>
                  </div>
                </div>
              )}

              {/* Step 3: Payment */}
              {currentStep === 2 && (
                <div className="space-y-6">
                  <h2 className="font-display text-xl mb-2">PAYMENT METHOD</h2>
                  <p className="text-sm text-muted-foreground mb-4">Choose your preferred payment option. All transactions are secure and encrypted.</p>

                  <RadioGroup value={paymentMethod} onValueChange={setPaymentMethod} className="space-y-3">
                    <div
                      className={cn(
                        'flex items-center gap-4 p-5 rounded-xl border-2 cursor-pointer transition-all hover:shadow-sm',
                        paymentMethod === 'card' ? 'border-primary bg-primary/5 shadow-sm' : 'border-border hover:border-primary/40'
                      )}
                      onClick={() => setPaymentMethod('card')}
                    >
                      <RadioGroupItem value="card" id="card" />
                      <Label htmlFor="card" className="flex items-center gap-4 flex-1 cursor-pointer">
                        <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center shrink-0">
                          <CreditCard className="h-5 w-5 text-primary" />
                        </div>
                        <div className="flex-1">
                          <p className="font-medium">Credit / Debit Card</p>
                          <p className="text-sm text-muted-foreground">Visa, Mastercard, RuPay</p>
                        </div>
                        {paymentMethod === 'card' && <CheckCircle className="h-5 w-5 text-primary shrink-0" />}
                      </Label>
                    </div>

                    <div
                      className={cn(
                        'flex items-center gap-4 p-5 rounded-xl border-2 cursor-pointer transition-all hover:shadow-sm',
                        paymentMethod === 'upi' ? 'border-primary bg-primary/5 shadow-sm' : 'border-border hover:border-primary/40'
                      )}
                      onClick={() => setPaymentMethod('upi')}
                    >
                      <RadioGroupItem value="upi" id="upi" />
                      <Label htmlFor="upi" className="flex items-center gap-4 flex-1 cursor-pointer">
                        <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center shrink-0">
                          <Wallet className="h-5 w-5 text-primary" />
                        </div>
                        <div className="flex-1">
                          <p className="font-medium">UPI</p>
                          <p className="text-sm text-muted-foreground">Google Pay, PhonePe, Paytm</p>
                        </div>
                        {paymentMethod === 'upi' && <CheckCircle className="h-5 w-5 text-primary shrink-0" />}
                      </Label>
                    </div>

                    <div
                      className={cn(
                        'flex items-center gap-4 p-5 rounded-xl border-2 cursor-pointer transition-all hover:shadow-sm',
                        paymentMethod === 'netbanking' ? 'border-primary bg-primary/5 shadow-sm' : 'border-border hover:border-primary/40'
                      )}
                      onClick={() => setPaymentMethod('netbanking')}
                    >
                      <RadioGroupItem value="netbanking" id="netbanking" />
                      <Label htmlFor="netbanking" className="flex items-center gap-4 flex-1 cursor-pointer">
                        <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center shrink-0">
                          <Building className="h-5 w-5 text-primary" />
                        </div>
                        <div className="flex-1">
                          <p className="font-medium">Net Banking</p>
                          <p className="text-sm text-muted-foreground">All major banks supported</p>
                        </div>
                        {paymentMethod === 'netbanking' && <CheckCircle className="h-5 w-5 text-primary shrink-0" />}
                      </Label>
                    </div>

                    <div
                      className={cn(
                        'flex items-center gap-4 p-5 rounded-xl border-2 cursor-pointer transition-all hover:shadow-sm',
                        paymentMethod === 'cod' ? 'border-primary bg-primary/5 shadow-sm' : 'border-border hover:border-primary/40'
                      )}
                      onClick={() => setPaymentMethod('cod')}
                    >
                      <RadioGroupItem value="cod" id="cod" />
                      <Label htmlFor="cod" className="flex items-center gap-4 flex-1 cursor-pointer">
                        <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center shrink-0">
                          <Banknote className="h-5 w-5 text-primary" />
                        </div>
                        <div className="flex-1">
                          <p className="font-medium">Cash on Delivery</p>
                          <p className="text-sm text-muted-foreground">Pay when you receive your order</p>
                        </div>
                        {paymentMethod === 'cod' && <CheckCircle className="h-5 w-5 text-primary shrink-0" />}
                      </Label>
                    </div>
                  </RadioGroup>

                  {paymentMethod === 'card' && (
                    <motion.div
                      initial={{ opacity: 0, height: 0 }}
                      animate={{ opacity: 1, height: 'auto' }}
                      className="space-y-4 p-5 bg-muted/50 rounded-xl border border-border"
                    >
                      <p className="text-sm font-medium flex items-center gap-2">
                        <Lock className="h-3.5 w-3.5" /> Card Details
                      </p>
                      <div>
                        <Label htmlFor="cardNumber">Card Number</Label>
                        <Input id="cardNumber" placeholder="4111 1111 1111 1111" className="mt-1 font-mono" />
                      </div>
                      <div>
                        <Label htmlFor="cardName">Name on Card</Label>
                        <Input id="cardName" placeholder="VIRAT KOHLI" className="mt-1 uppercase" />
                      </div>
                      <div className="grid grid-cols-2 gap-4">
                        <div>
                          <Label htmlFor="expiry">Expiry Date</Label>
                          <Input id="expiry" placeholder="MM/YY" className="mt-1 font-mono" />
                        </div>
                        <div>
                          <Label htmlFor="cvv">CVV</Label>
                          <Input id="cvv" type="password" placeholder="•••" maxLength={4} className="mt-1 font-mono" />
                        </div>
                      </div>
                    </motion.div>
                  )}

                  {paymentMethod === 'upi' && (
                    <motion.div
                      initial={{ opacity: 0, height: 0 }}
                      animate={{ opacity: 1, height: 'auto' }}
                      className="p-5 bg-muted/50 rounded-xl border border-border space-y-4"
                    >
                      <p className="text-sm font-medium">Enter your UPI ID</p>
                      <Input id="upiId" placeholder="yourname@upi" className="font-mono" />
                      <p className="text-xs text-muted-foreground">Example: mobilenumber@ybl, name@okicici, name@paytm</p>
                    </motion.div>
                  )}

                  {paymentMethod === 'netbanking' && (
                    <motion.div
                      initial={{ opacity: 0, height: 0 }}
                      animate={{ opacity: 1, height: 'auto' }}
                      className="p-5 bg-muted/50 rounded-xl border border-border"
                    >
                      <p className="text-sm font-medium mb-3">Select Your Bank</p>
                      <div className="grid grid-cols-2 gap-2">
                        {['SBI', 'HDFC Bank', 'ICICI Bank', 'Axis Bank', 'Kotak Bank', 'Bank of Baroda'].map((bank) => (
                          <div key={bank} className="p-3 rounded-lg border border-border hover:border-primary hover:bg-primary/5 cursor-pointer transition-colors text-sm text-center font-medium">
                            {bank}
                          </div>
                        ))}
                      </div>
                    </motion.div>
                  )}

                  {paymentMethod === 'cod' && (
                    <motion.div
                      initial={{ opacity: 0, height: 0 }}
                      animate={{ opacity: 1, height: 'auto' }}
                      className="p-4 bg-muted/50 rounded-xl border border-border"
                    >
                      <p className="text-sm text-muted-foreground">
                        💵 Pay the delivery partner in cash or via UPI when your order arrives. An additional ₹49 COD handling fee may apply.
                      </p>
                    </motion.div>
                  )}

                  <div className="flex gap-4">
                    <Button variant="outline" onClick={handlePrevStep} className="flex-1">
                      Back
                    </Button>
                    <Button
                      onClick={handlePlaceOrder}
                      disabled={isProcessing}
                      className="flex-1 bg-gradient-to-r from-primary to-accent hover:opacity-90"
                    >
                      {isProcessing ? (
                        <span className="flex items-center gap-2">
                          <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                          Processing...
                        </span>
                      ) : (
                        <>
                          <Lock className="h-4 w-4 mr-2" />
                          Place Order • {formatPrice(finalTotal)}
                        </>
                      )}
                    </Button>
                  </div>
                </div>
              )}
            </motion.div>
          </div>

          {/* Order Summary */}
          <div className="lg:col-span-1">
            <div className="bg-card rounded-2xl border border-border p-6 sticky top-24">
              <h2 className="font-display text-xl mb-6">ORDER SUMMARY</h2>

              {/* Items */}
              <div className="space-y-4 max-h-64 overflow-y-auto mb-6">
                {items.map((item) => (
                  <div key={item.product.id} className="flex gap-3">
                    <div className="w-16 h-16 rounded-lg overflow-hidden flex-shrink-0">
                      <img
                        src={item.product.image}
                        alt={item.product.name}
                        className="w-full h-full object-cover"
                      />
                    </div>
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium truncate">{item.product.name}</p>
                      <p className="text-xs text-muted-foreground">Qty: {item.quantity}</p>
                      <p className="text-sm font-semibold">
                        {formatPrice(item.product.price * item.quantity)}
                      </p>
                    </div>
                  </div>
                ))}
              </div>

              {/* Totals */}
              <div className="space-y-3 pt-4 border-t border-border">
                <div className="flex justify-between text-sm">
                  <span className="text-muted-foreground">Subtotal</span>
                  <span>{formatPrice(totalPrice)}</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-muted-foreground">Tax (GST 18%)</span>
                  <span>{formatPrice(tax)}</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-muted-foreground">Shipping</span>
                  <span>{shipping === 0 ? 'FREE' : formatPrice(shipping)}</span>
                </div>
                <div className="flex justify-between font-bold text-lg pt-3 border-t border-border">
                  <span>Total</span>
                  <span>{formatPrice(finalTotal)}</span>
                </div>
              </div>

              {/* Trust Badges */}
              <div className="mt-6 pt-6 border-t border-border space-y-3">
                <div className="flex items-center gap-3 text-sm text-muted-foreground">
                  <Lock className="h-4 w-4" />
                  <span>Secure 256-bit SSL encryption</span>
                </div>
                <div className="flex items-center gap-3 text-sm text-muted-foreground">
                  <Truck className="h-4 w-4" />
                  <span>Free delivery on orders above ₹2,000</span>
                </div>
                <div className="flex items-center gap-3 text-sm text-muted-foreground">
                  <Shield className="h-4 w-4" />
                  <span>100% authentic products</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  );
}
